# Favorite themes: hyper, smoooooth, terminal_app, vesper, monokai_charcoal,
# alabaster_dark, nightfly, dracula_plus
# alabaster(light theme)
import = [
    "~/.config/alacritty/themes/themes/hyper.toml"
]

[colors.cursor]
cursor = '0xffffff'

[font]
size = 10

[font.normal]
# family = "JetBrainsMono Nerd Font"
# family = "MonoLisa Nerd Font Mono"
family = "Hack Nerd Font"
# family = "FiraCode Nerd Font"
# family = "Monospace"
# style = "Regular"
# style = "Semi-Bold"
# style = "Medium"

[[keyboard.bindings]]
chars = "\u0003"
key = "C"
mods = "Control | Shift"

[[keyboard.bindings]]
key = "F11"
mods = "Control | Shift"
action = "ToggleFullscreen"

[[keyboard.bindings]]
chars = "\u0016"
key = "V"
mods = "Control | Shift"

[shell]
program = "/usr/bin/zsh"

[window]
startup_mode = "Maximized"
decorations = "none"
dynamic_title = false
# opacity = 0.9

# [env]
# TERM = "xterm-256color"

[debug]
log_level = "off"
