# This is the configuration file for Kitty terminal emulator.
# It contains various settings that control the behavior and appearance of the terminal.

# This setting removes the window decorations.
hide_window_decorations yes

# This command starts Kitty with remote control enabled and the layout set to 'tall'.
kitty -o allow_remote_control=yes -o enabled_layouts=tall

# These commented lines can be used to set a background image for the terminal, 
# adjust its tint and opacity, and choose the layout of the image.
# background_image /home/andrii-konotop/Terminal wallpapers/beach-waves.png
# background_tint 0.9
# background_image_layout scaled
# background_opacity 0.9

# These settings control the font used in the terminal.
# 'JetBrains Mono Nerd Font' is set as the font family.
# Italic and bold styles are enabled, and the font size is set to 14 points.
# font_family Consolas 
 
# italic_font auto
# bold_font auto
# bold_italic_font auto
# font_size 14

# background #282c34
# dynamic_background_opacity true


# Font configuration
# font_family Hack
font_family FiraCode Nerd Font
# font_family JetBrainsMono Nerd Font Mono 
bold_font auto 
italic_font auto 
bold_italic_font auto 
font_size 16

# This setting maps the 'f' key to toggle fullscreen mode in normal mode.
map normal f fullscreen

# This setting changes the cursor shape to 'block'.
cursor_shape block

# This setting enables URL detection in the terminal.
detect_urls yes

input_delay 0

# This setting controls the delay before the terminal is repainted.
repaint_delay 2

wayland_enable_ime no

# This setting disables synchronization with the monitor.
sync_to_monitor no

# This setting disables fast scroll detection.
fast_scroll_detect no

# BEGIN_KITTY_THEME
# Tango Dark
# include current-theme.conf
# END_KITTY_THEME
# cursor                          #FF7979
# cursor_text_color               #111111
