# background_image /home/sappchak/Pictures/Terminal/achuj_cat.png
# background_tint 0.97
# background_image_layout centered
# background_opacity 0.9

# background #282c34
# dynamic_background_opacity true

# Font configuration
# font_family Hack Nerd Font
# font_family FiraCode Nerd Font

# Font configuration
font_family JetBrainsMono Nerd Font
# bold_font JetBrainsMono Nerd Font Mono Bold
# italic_font JetBrainsMono Nerd Font Mono Italic
# bold_italic_font JetBrainsMono Nerd Font Mono Bold Italic

font_size 15

# Disable dynamic title
dynamic_title no

# This setting changes the cursor shape to 'block'.
cursor_shape block

# This setting enables URL detection in the terminal.
detect_urls no

# Disable audio bell
enable_audio_bell no

# 0 disables it; -1 enables it
confirm_os_window_close 0

# Improve perfomance
input_delay 0
repaint_delay 2
sync_to_monitor no

map ctrl+equal change_font_size all +1.0
map ctrl+minus change_font_size all -1.0

# BEGIN_KITTY_THEME
# Adwaita dark
include current-theme.conf
# END_KITTY_THEME
# cursor                          #FF7979
# cursor_text_color               #111111
# background                #000000
# cursor                    #deddda
# cursor_text_color         #000000
