# Enable 256 colors and RGB support
set-option -g default-terminal "screen-256color"
set -as terminal-features ",*:RGB"
set -ag terminal-overrides ",xterm-256color:RGB"

# Set escape time
set -s escape-time 0

# Set status bar color and position
set-option -g status-style bg=default
set-option -g status-position bottom
set-option -g automatic-rename on
set-option -g status-right ''
set-option -g status-justify left
set-option -g status-left-length 20

# Set pane styles
set -g mode-style bg=colour183,fg=black
set -g pane-active-border-style bg=colour183,fg=default
set -g pane-border-style bg=default,fg=default
setw -g window-status-current-style bg=default,fg=default

# Set message styles
set -g message-style bg=colour183,fg=black
set -g message-command-style bg=colour183,fg=black

# Set prefix and unbind default prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Set bindings for new window and split window
unbind %
unbind '"'
bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Set history limit and enable mouse
set -g history-limit 10000
set -g mouse on

# Set bindings for pane selection
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Set binding for reloading config
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded.."

# Set plugins
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tpm'

# Set continuum restore
set -g @continuum-restore 'on'

# Run TPM
run '~/.config/tmux/plugins/tpm/tpm'
